image: Visual Studio 2019

environment:
  nodejs_version: 14
  platform: x86

install:
- setx APPVEYOR_BUILD_AGENT_LATEST_VERSION_TEST 6.3.2.2919 /m
- setx APPVEYOR_BUILD_AGENT_LATEST_URL_TEST https://github.com/appveyor/ci/releases/download/build-agent-v6.3.2%%2B2919/AppveyorBuildAgent.zip /m
- appveyor version
- ps: Start-Sleep -s 5; Restart-Computer
- ps: Start-Sleep -s 5
- appveyor version
- ps: Start-Sleep -s 600

build: off

test_script:
- test.cmd
